#TODO: to put relevant description to each element in this yaml file.
depth_encoder:
  model_type: "resnet" # choices: "resnet", "efficientnet", "convnext_L"
  num_layers: 50 # number of ResNet layers used as depth encoder.
  num_features: 256 # ResNet feature dim; basically these is used for decoder and upsampleBN; see the diagram.
  model_dim: 32 # these are basically the number of channels of the resulted feature map S from the ResNet depth encoder.
  dec_channels: [1024, 512, 256, 128] # decoder channels in Unet for the ConvNeXt-L depth encoder.
depth_decoder:
  patch_size: 16 # patch size before ViT: "we first apply a convolution of kernel size p x p and stride = p to S"; p=16 in paper!
  dim_out: 64 #..
  query_nums: 64 #..
  min_depth: 0.001 #..
  max_depth: 80.0 #...

pretrained_models_folder: '/home/ANT.AMAZON.COM/grigiono/Desktop/SQLdepth/src/pretrained/KITTI_ResNet50_192x640_models'
image_path_inference: '/home/ANT.AMAZON.COM/grigiono/Desktop/SQLdepth/src/inference/img2.png'
image_extension_inference: "png"
use_cuda: False
im_sz: [192, 640]